=== T0shiro/JSONtoXML/Schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {},
  "id": "http://example.com/example.json",
  "items": {
    "id": "/items",
    "properties": {
      "data": {
        "id": "/items/properties/data",
        "properties": {
          "budget": {
            "id": "/items/properties/data/properties/budget",
            "type": "integer"
          },
          "contracts": {
            "id": "/items/properties/data/properties/contracts",
            "items": {
              "id": "/items/properties/data/properties/contracts/items",
              "properties": {
                "amount": {
                  "id": "/items/properties/data/properties/contracts/items/properties/amount",
                  "type": "integer"
                },
                "resource": {
                  "id": "/items/properties/data/properties/contracts/items/properties/resource",
                  "type": "string"
                }
              },
              "type": "object"
            },
            "type": "array"
          },
          "heading": {
            "id": "/items/properties/data/properties/heading",
            "type": "string"
          },
          "men": {
            "id": "/items/properties/data/properties/men",
            "type": "integer"
          }
        },
        "type": "object"
      },
      "meth": {
        "id": "/items/properties/meth",
        "type": "string"
      },
      "part": {
        "id": "/items/properties/part",
        "type": "string"
      },
      "time": {
        "id": "/items/properties/time",
        "type": "integer"
      }
    },
    "type": "object"
  },
  "type": "array"
}

=== T0shiro/JSONtoXML/jsonIADA.json
[{
  "data": {
    "heading": "E",
    "men": 15,
    "contracts": [
      {
        "amount": 2,
        "resource": "GLASS"
      },
      {
        "amount": 15,
        "resource": "RUM"
      },
      {
        "amount": 100,
        "resource": "FRUITS"
      },
      {
        "amount": 500,
        "resource": "FLOWER"
      },
      {
        "amount": 12000,
        "resource": "WOOD"
      },
      {
        "amount": 2000,
        "resource": "FUR"
      }
    ],
    "budget": 40000
  },
  "part": "Engine",
  "time": 1488737658802,
  "meth": "initialize"
},{
  "data": {
    "action": "echo",
    "parameters": {"direction": "E"}
  },
  "part": "Explorer",
  "time": 1488737658810,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {
      "found": "OUT_OF_RANGE",
      "range": 52
    },
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658810,
  "meth": "takeDecision"
},{
  "data": {
    "action": "echo",
    "parameters": {"direction": "N"}
  },
  "part": "Explorer",
  "time": 1488737658810,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 5,
    "extras": {
      "found": "OUT_OF_RANGE",
      "range": 0
    },
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658810,
  "meth": "takeDecision"
},{
  "data": {
    "action": "echo",
    "parameters": {"direction": "S"}
  },
  "part": "Explorer",
  "time": 1488737658811,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 5,
    "extras": {
      "found": "OUT_OF_RANGE",
      "range": 52
    },
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658811,
  "meth": "takeDecision"
},{
  "data": {
    "action": "echo",
    "parameters": {"direction": "N"}
  },
  "part": "Explorer",
  "time": 1488737658813,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {
      "found": "OUT_OF_RANGE",
      "range": 0
    },
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658813,
  "meth": "takeDecision"
},{
  "data": {
    "action": "echo",
    "parameters": {"direction": "S"}
  },
  "part": "Explorer",
  "time": 1488737658813,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {
      "found": "OUT_OF_RANGE",
      "range": 52
    },
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658813,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658813,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 3,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658813,
  "meth": "takeDecision"
},{
  "data": {
    "action": "echo",
    "parameters": {"direction": "N"}
  },
  "part": "Explorer",
  "time": 1488737658813,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 5,
    "extras": {
      "found": "OUT_OF_RANGE",
      "range": 0
    },
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658813,
  "meth": "takeDecision"
},{
  "data": {
    "action": "echo",
    "parameters": {"direction": "S"}
  },
  "part": "Explorer",
  "time": 1488737658813,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 7,
    "extras": {
      "found": "OUT_OF_RANGE",
      "range": 52
    },
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658814,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658814,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658814,
  "meth": "takeDecision"
},{
  "data": {
    "action": "echo",
    "parameters": {"direction": "N"}
  },
  "part": "Explorer",
  "time": 1488737658814,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {
      "found": "OUT_OF_RANGE",
      "range": 0
    },
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658814,
  "meth": "takeDecision"
},{
  "data": {
    "action": "echo",
    "parameters": {"direction": "S"}
  },
  "part": "Explorer",
  "time": 1488737658814,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 5,
    "extras": {
      "found": "OUT_OF_RANGE",
      "range": 52
    },
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658814,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658814,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 3,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658814,
  "meth": "takeDecision"
},{
  "data": {
    "action": "echo",
    "parameters": {"direction": "N"}
  },
  "part": "Explorer",
  "time": 1488737658814,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 6,
    "extras": {
      "found": "OUT_OF_RANGE",
      "range": 0
    },
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658814,
  "meth": "takeDecision"
},{
  "data": {
    "action": "echo",
    "parameters": {"direction": "S"}
  },
  "part": "Explorer",
  "time": 1488737658814,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 6,
    "extras": {
      "found": "GROUND",
      "range": 33
    },
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658815,
  "meth": "takeDecision"
},{
  "data": {
    "action": "heading",
    "parameters": {"direction": "S"}
  },
  "part": "Explorer",
  "time": 1488737658815,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658815,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 6,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 3,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 6,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 2,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 2,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 5,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 6,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 2,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 3,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 3,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658816,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658817,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658817,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658817,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658817,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658817,
  "meth": "takeDecision"
},{
  "data": {
    "cost": 4,
    "extras": {},
    "status": "OK"
  },
  "part": "Engine",
  "time": 1488737658817,
  "meth": "takeDecision"
},{
  "data": {"action": "fly"},
  "part": "Explorer",
  "time": 1488737658817,
